import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Form from '../components/Form';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ingredivert</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Let&apos;s Ingredivert!</h1>
        <Form />
      </main>
    </div>
  );
}
